# Generated by Django 5.2.7 on 2026-01-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplineprofile",
            name="push_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
